#!/usr/bin/env php
<?php

require __DIR__.'/system/console.php';

use Symfony\Component\Console\Application;

$application = new Application('OpenCart Console', '1.0 beta');
$application->add(new \Console\repl());
$application->add(new \Console\product());
$application->add(new \Console\order());

$application->run();