<?php

/**
 * @copyright        2018 opencart.cn - All Rights Reserved
 * @author:          Sam Chen <sam.chen@opencart.cn>
 * @created:         2018-01-16 20:14:21
 * @modified by:     Sam Chen <sam.chen@opencart.cn>
 * @modified:        2018-01-16 20:25:18
 */

class ControllerCommonCustomCss extends Controller
{
    public function index()
    {
        // theme_{CODE}_css
        $css = config('theme_' . config('config_theme') . "_css");
        if (!$css) {
            return false;
        }

        $path = 'cache/';
        $prefix = config('config_theme') . '.custom';

        $pattern = DIR_IMAGE . $path . $prefix . '.*.css';
        $files = glob($pattern);
        if (count($files) == 1) {
            return $path . basename($files[0]);
        } else { // Remove all cache css when more than one cache file found
            array_map('unlink', glob($pattern));
        }

        // Output css to cache file
        $file = $prefix . '.' . strtolower(uniqid()) . '.css';
        $relative_path = $path . $file;

        $file = fopen(DIR_IMAGE . $relative_path, 'w');
        $comment = '/*[' . date('Y/m/d H:i:s') . '] This file is generated by code, DO NOT edit this file! */'. PHP_EOL;
        $output = $comment . html_entity_decode($css, ENT_QUOTES, 'UTF-8');
        fwrite($file, $output);
        fclose($file);
        return $relative_path;
    }
}
